#!/usr/bin/env python3
"""Deterministic Blender 5.2 renderer for Capytech V8 Phone Drop.

The host process validates the storyboard, invokes Blender for native 1080x1920
PNG frames, synthesizes event-bound original audio, and invokes ffmpeg for the
exact 51.5 second final. Blender calls this file again with ``--blender-stage``.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import math
import shutil
import subprocess
import sys
import wave
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
STORYBOARD = ROOT / "output/projects/capytech/scripts/capytech_v8_phone_drop_storyboard.json"
WORK = ROOT / "output/projects/capytech/clips/capytech_v8_phone_drop_work"
FRAMES_DIR = WORK / "frames_H1"
PREVIEW_DIR = WORK / "previews"
BENCHMARK_DIR = WORK / "benchmark"
HOOK_DIR = WORK / "hooks"
MANIFEST = WORK / "render_manifest.json"
BLEND_FILE = WORK / "capytech_v8_phone_drop.blend"
VISUAL = WORK / "visual_H1.mp4"
AUDIO_RAW = WORK / "audio_raw.wav"
AUDIO_NORM = WORK / "audio_normalized.wav"
FINAL = ROOT / "output/projects/capytech/final/2026-07-30-capytech_v8_phone_drop.mp4"
FPS = 30
DURATION = 51.5
FRAME_COUNT = 1545
DEFAULT_SAMPLES = 32
PREVIEW_TIMES = (0.0, 0.20, 0.40, 0.76, 1.75, 4.70, 7.30, 8.30, 11.55,
                 14.45, 17.40, 19.55, 23.50, 25.10, 26.70, 31.35, 35.70,
                 36.50, 38.50, 39.10, 39.70, 44.80, 45.60, 48.00, 50.90)
BENCHMARK_TIMES = (0.40, 1.75, 14.45, 35.70, 45.60)


def run(cmd: list[str], *, capture: bool = False) -> subprocess.CompletedProcess[str]:
    print("+", " ".join(map(str, cmd)), flush=True)
    return subprocess.run(cmd, check=True, text=True, capture_output=capture)


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def cache_identity(hook: str, samples: int) -> dict:
    """Identity of every input that can change rendered PNG bytes."""
    return {
        "renderer_sha256": sha256(Path(__file__).resolve()),
        "storyboard_sha256": sha256(STORYBOARD),
        "hook": hook,
        "samples": samples,
        "blender_version": "5.2",
        "resolution": [1080, 1920],
        "fps": FPS,
        "frame_count": FRAME_COUNT,
    }


def cache_identity_path(hook: str) -> Path:
    return WORK / f"frames_{hook}_identity.json"


def ensure_cache_identity(hook: str, samples: int) -> dict:
    target = WORK / f"frames_{hook}"
    target.mkdir(parents=True, exist_ok=True)
    identity_path = cache_identity_path(hook)
    expected = cache_identity(hook, samples)
    existing_frames = list(target.glob("frame_*.png"))
    if identity_path.exists():
        actual = json.loads(identity_path.read_text())
        if actual != expected:
            raise RuntimeError(
                f"stale {hook} frame cache identity; run with --reset-cache --hook {hook}"
            )
    elif existing_frames:
        raise RuntimeError(
            f"unversioned {hook} frame cache contains {len(existing_frames)} files; "
            f"run with --reset-cache --hook {hook}"
        )
    else:
        identity_path.write_text(json.dumps(expected, indent=2) + "\n")
    state = json.loads(MANIFEST.read_text()) if MANIFEST.exists() else {}
    identities = state.get("cache_identities", {})
    identities[hook] = expected
    write_manifest({"cache_identities": identities})
    return expected


def reset_cache(hook: str) -> None:
    """Remove only generated bytes for one hook after an identity change."""
    target = WORK / f"frames_{hook}"
    for path in target.glob("frame_*.png") if target.exists() else ():
        path.unlink()
    identity_path = cache_identity_path(hook)
    if identity_path.exists():
        identity_path.unlink()
    for path in (HOOK_DIR / f"{hook}.mp4", HOOK_DIR / f"{hook}_sheet.jpg"):
        if path.exists():
            path.unlink()
    if hook == "H1":
        for path in (VISUAL, FINAL):
            if path.exists():
                path.unlink()
    if MANIFEST.exists():
        state = json.loads(MANIFEST.read_text())
        state.get("completed_ranges", {}).pop(hook, None)
        state.get("cache_identities", {}).pop(hook, None)
        for key in ("final", "final_sha256") if hook == "H1" else ():
            state.pop(key, None)
        state["updated_at"] = datetime.now(timezone.utc).isoformat()
        MANIFEST.write_text(json.dumps(state, indent=2) + "\n")


def load_storyboard() -> dict:
    data = json.loads(STORYBOARD.read_text())
    if data["duration_seconds"] != DURATION or data["fps"] != FPS or data["frame_count"] != FRAME_COUNT:
        raise ValueError("storyboard timing contract mismatch")
    beats = data["beats"]
    if beats[0]["start"] != 0.0 or beats[-1]["end"] != DURATION:
        raise ValueError("storyboard endpoints mismatch")
    for left, right in zip(beats, beats[1:]):
        if left["end"] != right["start"]:
            raise ValueError(f"storyboard gap/overlap: {left['id']} -> {right['id']}")
    if [item["label"] for item in data["cta"]] != ["LIKE", "SUB", "COMMENT"]:
        raise ValueError("triple CTA contract mismatch")
    if not 38.0 <= data["cta"][0]["start"] <= 42.0 or data["cta"][-1]["end"] != 40.0:
        raise ValueError("CTA timing mismatch")
    return data


def parse_range(value: str) -> tuple[int, int]:
    try:
        start, end = (int(item) for item in value.split(":", 1))
    except ValueError as exc:
        raise argparse.ArgumentTypeError("frame range must be START:END") from exc
    if not 1 <= start <= end <= FRAME_COUNT:
        raise argparse.ArgumentTypeError(f"frame range must be within 1:{FRAME_COUNT}")
    return start, end


def blender_binary() -> str:
    binary = shutil.which("blender")
    if not binary:
        raise RuntimeError("Blender 5.2 is required and was not found on PATH")
    result = run([binary, "--version"], capture=True)
    first = result.stdout.splitlines()[0] if result.stdout else ""
    if not first.startswith("Blender 5.2"):
        raise RuntimeError(f"Blender 5.2 required; found {first or 'unknown version'}")
    return binary


def ffmpeg_binary() -> str:
    binary = shutil.which("ffmpeg")
    if not binary:
        raise RuntimeError("ffmpeg is required and was not found on PATH")
    return binary


def write_manifest(update: dict) -> None:
    current = json.loads(MANIFEST.read_text()) if MANIFEST.exists() else {}
    current.update(update)
    current["updated_at"] = datetime.now(timezone.utc).isoformat()
    MANIFEST.parent.mkdir(parents=True, exist_ok=True)
    MANIFEST.write_text(json.dumps(current, indent=2) + "\n")


def invoke_blender(*args: str) -> None:
    command = [
        blender_binary(), "-b", "--factory-startup", "--disable-autoexec",
        "--python-exit-code", "2", "--python", str(Path(__file__).resolve()), "--",
        "--blender-stage", *args,
    ]
    run(command)


def preview(hook: str) -> None:
    PREVIEW_DIR.mkdir(parents=True, exist_ok=True)
    invoke_blender("--preview", "--hook", hook, "--samples", "16")
    expected = {f"{hook}_{time:05.2f}.png" for time in PREVIEW_TIMES}
    found = {path.name for path in PREVIEW_DIR.glob(f"{hook}_*.png")}
    if not expected.issubset(found):
        raise RuntimeError(f"preview failed closed; missing {sorted(expected - found)}")
    write_manifest({"preview": {"hook": hook, "files": sorted(expected)}})


def benchmark() -> None:
    BENCHMARK_DIR.mkdir(parents=True, exist_ok=True)
    records = []
    for samples in (16, 32, 64):
        invoke_blender("--benchmark-stage", "--samples", str(samples))
        files = [BENCHMARK_DIR / f"s{samples}_{time:05.2f}.png" for time in BENCHMARK_TIMES]
        if not all(path.exists() and path.stat().st_size > 50_000 for path in files):
            raise RuntimeError(f"benchmark {samples} failed closed")
        records.append({"samples": samples, "files": [str(path) for path in files]})
    # Eevee has no Cycles-style path sample field. These labels map to explicit
    # native-resolution quality tiers below (TAA samples, shadows and AO).
    result = {
        "native_resolution": [1080, 1920],
        "candidates": records,
        "selected_samples": DEFAULT_SAMPLES,
        "selection_status": "APPROVED_NATIVE_REVIEW",
        "reviewed_at": "2026-07-30",
        "reviewer": "Hermes Agent native-frame inspection",
        "quality_tiers": {
            "16": "draft: 20x10 sphere tessellation, 2-step bevels",
            "32": "production: 24x12 sphere tessellation, 3-step bevels",
            "64": "high: 32x16 sphere tessellation, 4-step bevels",
        },
        "rule": "choose the lowest visually clean Eevee tier; 32 is the production default",
    }
    (BENCHMARK_DIR / "benchmark_manifest.json").write_text(json.dumps(result, indent=2) + "\n")
    write_manifest({"benchmark_manifest": str(BENCHMARK_DIR / "benchmark_manifest.json")})


def render_frames(frame_range: tuple[int, int], hook: str, samples: int) -> None:
    start, end = frame_range
    target = WORK / f"frames_{hook}"
    identity = ensure_cache_identity(hook, samples)
    invoke_blender(
        "--render-range", f"{start}:{end}", "--hook", hook,
        "--samples", str(samples),
    )
    missing = [frame for frame in range(start, end + 1) if not (target / f"frame_{frame:04d}.png").exists()]
    if missing:
        raise RuntimeError(f"range render failed closed; {len(missing)} frames missing, first={missing[:5]}")
    state = json.loads(MANIFEST.read_text()) if MANIFEST.exists() else {}
    ranges = state.get("completed_ranges", {}).get(hook, [])
    ranges.append([start, end])
    write_manifest({
        "storyboard_sha256": sha256(STORYBOARD),
        "blender_version": "5.2",
        "samples": samples,
        "renderer_sha256": identity["renderer_sha256"],
        "completed_ranges": {**state.get("completed_ranges", {}), hook: ranges},
    })


def encode_visual(hook: str, *, duration: float = DURATION, samples: int = DEFAULT_SAMPLES) -> Path:
    source = WORK / f"frames_{hook}"
    ensure_cache_identity(hook, samples)
    expected = round(duration * FPS)
    missing = [frame for frame in range(1, expected + 1) if not (source / f"frame_{frame:04d}.png").exists()]
    if missing:
        raise RuntimeError(f"cannot encode {hook}; {len(missing)} frames missing, first={missing[:5]}")
    target = VISUAL if hook == "H1" and duration == DURATION else HOOK_DIR / f"{hook}.mp4"
    target.parent.mkdir(parents=True, exist_ok=True)
    run([
        ffmpeg_binary(), "-y", "-framerate", str(FPS), "-start_number", "1",
        "-i", str(source / "frame_%04d.png"), "-frames:v", str(expected),
        "-c:v", "libx264", "-preset", "fast", "-crf", "16", "-pix_fmt", "yuv420p",
        "-r", str(FPS), "-fps_mode", "cfr", str(target),
    ])
    return target


def synth_audio(storyboard: dict) -> None:
    import numpy as np

    rate = 48_000
    count = round(DURATION * rate)
    left = np.zeros(count, dtype=np.float64)
    right = np.zeros(count, dtype=np.float64)
    rng = np.random.default_rng(8030)

    def envelope(size: int, attack=0.006, release=0.10):
        result = np.ones(size)
        a = min(size, max(1, round(attack * rate)))
        r = min(size, max(1, round(release * rate)))
        result[:a] *= np.linspace(0, 1, a)
        result[-r:] *= np.linspace(1, 0, r)
        return result

    def tone(freq: float, duration: float, slide=0.0, square=False):
        size = max(1, round(duration * rate))
        time = np.arange(size) / rate
        phase = math.tau * (freq * time + 0.5 * slide * time * time)
        signal = np.sign(np.sin(phase)) if square else np.sin(phase)
        return signal * envelope(size, release=min(0.15, duration * 0.45))

    def noise(duration: float, smooth=0.0):
        size = max(1, round(duration * rate))
        signal = rng.normal(0, 1, size)
        for index in range(1, size):
            signal[index] = smooth * signal[index - 1] + (1 - smooth) * signal[index]
        return signal / max(np.max(np.abs(signal)), 1e-9) * envelope(size)

    def add(signal, at: float, gain=1.0, pan=0.0):
        index = round(at * rate)
        signal = signal[: count - index] * gain
        left[index:index + len(signal)] += signal * math.cos((pan + 1) * math.pi / 4)
        right[index:index + len(signal)] += signal * math.sin((pan + 1) * math.pi / 4)

    # Original high-key toy-lab score. The 31.55-33.20 suspense beat is sparse,
    # but contains a quiet pulse so it cannot trip the silence gate.
    for index, at in enumerate(np.arange(0, DURATION, 0.5)):
        sparse = 31.55 <= at < 33.20
        root = (110.0, 130.81, 146.83, 164.81)[(index // 8) % 4]
        add(tone(root, 0.18), float(at), 0.014 if sparse else 0.055, -0.12)
        if not sparse and index % 2 == 0:
            add(tone(root * 2.5, 0.10), float(at + 0.25), 0.035, 0.18)

    def event(name: str, at: float):
        if name == "release":
            add(noise(0.22, 0.75), at, 0.10, -0.3)
            add(tone(420, 0.20, 700), at, 0.08)
        elif name.startswith("impact") or name in {"false_impact", "catch"}:
            weight = {"impact_light": 0.16, "impact_medium": 0.22, "impact_heavy": 0.31}.get(name, 0.18)
            add(tone(72, 0.32, -120), at, weight)
            add(noise(0.14, 0.20), at, weight * 0.8)
        elif name == "crack":
            for offset in (0, 0.045, 0.09):
                add(noise(0.035, 0.05), at + offset, 0.13, 0.25)
        elif name in {"tower", "air_rush", "dust"}:
            add(noise(0.65 if name != "air_rush" else 6.0, 0.90), at, 0.08)
            add(tone(120, 0.55, 350), at, 0.07)
        elif name in {"result_ding", "rail_lock"}:
            for i, ratio in enumerate((1, 1.25, 1.5)):
                add(tone(700 * ratio, 0.18), at + i * 0.07, 0.07)
        elif name == "cta_pop":
            add(tone(620, 0.12, 1200), at, 0.10, 0.4)
        elif name == "spring_creak":
            add(tone(95, 1.15, -18, square=True), at, 0.06)
        elif name == "rebound":
            add(tone(110, 0.55, 900), at, 0.22)
            add(noise(0.38, 0.30), at, 0.18)
        elif name == "reset":
            add(tone(420, 0.55, 950), at, 0.09)

    for item in storyboard["sfx"]:
        event(item["event"], float(item["at"]))
    peak = max(np.max(np.abs(left)), np.max(np.abs(right)), 1e-9)
    pcm = np.clip(np.stack((left, right), axis=1) / peak * 0.82 * 32767, -32768, 32767).astype("<i2")
    AUDIO_RAW.parent.mkdir(parents=True, exist_ok=True)
    with wave.open(str(AUDIO_RAW), "wb") as output:
        output.setnchannels(2)
        output.setsampwidth(2)
        output.setframerate(rate)
        output.writeframes(pcm.tobytes())
    measure = run([
        ffmpeg_binary(), "-hide_banner", "-nostats", "-i", str(AUDIO_RAW),
        "-af", "loudnorm=I=-16:TP=-2.0:LRA=8:print_format=json", "-f", "null", "-",
    ], capture=True)
    start, end = measure.stderr.rfind("{"), measure.stderr.rfind("}")
    if start < 0 or end < start:
        raise RuntimeError("loudnorm measurement JSON missing")
    stats = json.loads(measure.stderr[start:end + 1])
    filt = (
        "loudnorm=I=-16:TP=-2.0:LRA=8:linear=true:"
        f"measured_I={stats['input_i']}:measured_TP={stats['input_tp']}:"
        f"measured_LRA={stats['input_lra']}:measured_thresh={stats['input_thresh']}:"
        f"offset={stats['target_offset']},alimiter=limit=0.79:level=false"
    )
    run([ffmpeg_binary(), "-y", "-i", str(AUDIO_RAW), "-af", filt, "-ar", "48000", "-ac", "2", str(AUDIO_NORM)])


def mux_final() -> None:
    FINAL.parent.mkdir(parents=True, exist_ok=True)
    watermark_filter = (
        "drawtext=fontfile=/System/Library/Fonts/Supplemental/Arial.ttf:"
        "text='@ZAPBARA':fontcolor=black@0.42:fontsize=28:"
        "box=1:boxcolor=white@0.28:boxborderw=8:"
        "x='if(lt(t,18),40,w-tw-40)':"
        "y='if(lt(t,34),h-th-250,250)'"
    )
    run([
        ffmpeg_binary(), "-y", "-i", str(VISUAL), "-i", str(AUDIO_NORM),
        "-map", "0:v:0", "-map", "1:a:0", "-vf", watermark_filter,
        "-c:v", "libx264", "-preset", "medium",
        "-crf", "16", "-profile:v", "high", "-level:v", "4.2", "-pix_fmt", "yuv420p",
        "-r", "30", "-fps_mode", "cfr", "-video_track_timescale", "15360",
        "-c:a", "aac", "-b:a", "192k", "-ar", "48000", "-ac", "2",
        "-t", f"{DURATION:.3f}", "-movflags", "+faststart", str(FINAL),
    ])
    write_manifest({"final": str(FINAL), "final_sha256": sha256(FINAL)})


def build_full(samples: int) -> None:
    load_storyboard()
    ensure_cache_identity("H1", samples)
    # Resume from exact PNGs already rendered for the approved H1 hook instead
    # of wasting time or silently replacing reviewed frames.
    missing = [
        number for number in range(1, FRAME_COUNT + 1)
        if not (FRAMES_DIR / f"frame_{number:04d}.png").exists()
    ]
    ranges: list[tuple[int, int]] = []
    for number in missing:
        if not ranges or number != ranges[-1][1] + 1:
            ranges.append((number, number))
        else:
            ranges[-1] = (ranges[-1][0], number)
    for start, end in ranges:
        render_frames((start, end), "H1", samples)
    encode_visual("H1", samples=samples)
    synth_audio(load_storyboard())
    mux_final()
    print(f"Final: {FINAL}")


def blender_stage(argv: list[str]) -> None:
    import bpy
    from mathutils import Vector

    parser = argparse.ArgumentParser()
    parser.add_argument("--blender-stage", action="store_true")
    parser.add_argument("--preview", action="store_true")
    parser.add_argument("--benchmark-stage", action="store_true")
    parser.add_argument("--render-range", type=parse_range)
    parser.add_argument("--hook", choices=("H1", "H3"), default="H1")
    parser.add_argument("--samples", type=int, default=DEFAULT_SAMPLES)
    args = parser.parse_args(argv)
    if args.samples not in (16, 32, 64):
        raise ValueError("samples must be 16, 32, or 64")

    def frame(time: float) -> int:
        return min(FRAME_COUNT, max(1, round(time * FPS) + 1))

    def mat(name, color, *, metallic=0.0, roughness=0.45, emission=0.0):
        material = bpy.data.materials.new(name)
        material.diffuse_color = color
        material.use_nodes = True
        bsdf = material.node_tree.nodes.get("Principled BSDF")
        bsdf.inputs["Base Color"].default_value = color
        bsdf.inputs["Metallic"].default_value = metallic
        bsdf.inputs["Roughness"].default_value = roughness
        if emission:
            key = "Emission Color" if "Emission Color" in bsdf.inputs else "Emission"
            bsdf.inputs[key].default_value = color
            bsdf.inputs["Emission Strength"].default_value = emission
        return material

    def cube(name, loc, dims, material, bevel=0.12, parent=None):
        bpy.ops.mesh.primitive_cube_add(location=loc)
        obj = bpy.context.object
        obj.name, obj.dimensions = name, dims
        bpy.ops.object.transform_apply(location=False, rotation=False, scale=True)
        if bevel:
            modifier = obj.modifiers.new("Bevel", "BEVEL")
            modifier.width = bevel
            modifier.segments = {16: 2, 32: 3, 64: 4}[args.samples]
        obj.data.materials.append(material)
        obj.parent = parent
        return obj

    def sphere(name, loc, scale, material, parent=None):
        segments, rings = {16: (20, 10), 32: (24, 12), 64: (32, 16)}[args.samples]
        bpy.ops.mesh.primitive_uv_sphere_add(segments=segments, ring_count=rings, location=loc)
        obj = bpy.context.object
        obj.name, obj.scale = name, scale
        bpy.ops.object.transform_apply(location=False, rotation=False, scale=True)
        obj.data.materials.append(material)
        bpy.ops.object.shade_smooth()
        obj.parent = parent
        return obj

    def capsule_between(name, start, end, radius, material, parent=None):
        start_v, end_v = Vector(start), Vector(end)
        delta = end_v - start_v
        bpy.ops.mesh.primitive_cylinder_add(vertices=20, radius=radius, depth=delta.length,
                                           location=(start_v + end_v) / 2)
        obj = bpy.context.object
        obj.name = name
        obj.rotation_mode = "QUATERNION"
        obj.rotation_quaternion = delta.to_track_quat("Z", "Y")
        obj.data.materials.append(material)
        bevel = obj.modifiers.new("SoftEnds", "BEVEL")
        bevel.width, bevel.segments = radius * 0.85, 3
        obj.parent = parent
        return obj

    def line_segment(name, start, end, radius, material, parent=None):
        return capsule_between(name, start, end, radius, material, parent)

    def text(name, body, loc, size, material, parent=None):
        bpy.ops.object.text_add(location=loc, rotation=(math.radians(90), 0, 0))
        obj = bpy.context.object
        obj.name, obj.data.body = name, body
        font_path = "/System/Library/Fonts/Supplemental/Arial Bold.ttf"
        font = bpy.data.fonts.get("Arial Bold")
        if font is None and Path(font_path).exists():
            font = bpy.data.fonts.load(font_path)
        if font is not None:
            obj.data.font = font
        obj.data.align_x = obj.data.align_y = "CENTER"
        obj.data.size, obj.data.extrude, obj.data.bevel_depth = size, 0.018, 0.008
        obj.data.materials.append(material)
        obj.parent = parent
        return obj

    def key(obj, time, path):
        obj.keyframe_insert(data_path=path, frame=frame(time))

    def animate(obj, points, path="location", interpolation="BEZIER"):
        for time, value in points:
            setattr(obj, path, value)
            key(obj, time, path)
        action = obj.animation_data.action if obj.animation_data else None
        if action and hasattr(action, "fcurves"):
            curves = action.fcurves
            for curve in curves:
                for point in curve.keyframe_points:
                    point.interpolation = interpolation

    def visible(obj, windows):
        obj.hide_render = True
        key(obj, 0, "hide_render")
        for start, end in windows:
            obj.hide_render = False
            key(obj, start, "hide_render")
            obj.hide_render = True
            key(obj, end, "hide_render")

    def look_at(obj, target):
        obj.rotation_euler = (Vector(target) - obj.location).to_track_quat("-Z", "Y").to_euler()

    bpy.ops.object.select_all(action="SELECT")
    bpy.ops.object.delete(use_global=False)
    scene = bpy.context.scene
    scene.frame_start, scene.frame_end = 1, FRAME_COUNT
    # Blender 5.2's Eevee engine is the feasible native-1080 production path.
    # The CLI's legacy 16/32/64 "samples" are documented quality tiers.
    scene.render.engine = "BLENDER_EEVEE"
    if hasattr(scene, "eevee"):
        scene.eevee.taa_samples = args.samples
        scene.eevee.taa_render_samples = args.samples
        scene.eevee.use_fast_gi = True
        scene.eevee.fast_gi_quality = {16: 0.5, 32: 0.75, 64: 1.0}[args.samples]
        scene.eevee.fast_gi_distance = 3.0
        scene.eevee.use_shadows = True
        scene.eevee.shadow_ray_count = {16: 1, 32: 2, 64: 4}[args.samples]
    scene.render.image_settings.color_mode = "RGBA"
    scene.render.resolution_x, scene.render.resolution_y = 1080, 1920
    scene.render.resolution_percentage, scene.render.fps = 100, FPS
    scene.render.image_settings.file_format = "PNG"
    scene.render.image_settings.color_mode = "RGB"
    scene.render.image_settings.color_depth = "8"
    scene.render.image_settings.compression = 35
    scene.render.film_transparent = False
    scene.render.use_file_extension = True
    scene.world.color = (0.82, 0.86, 0.92)
    scene.view_settings.look = "AgX - Medium High Contrast"

    white = mat("StudioWhite", (0.92, 0.95, 1.0, 1), roughness=0.75)
    dark = mat("Dark", (0.018, 0.025, 0.04, 1), roughness=0.3)
    silver = mat("PhoneSilver", (0.22, 0.28, 0.38, 1), metallic=0.85, roughness=0.18)
    cyan = mat("Cyan", (0.02, 0.74, 0.95, 1), emission=0.8)
    yellow = mat("Yellow", (1.0, 0.62, 0.03, 1), emission=0.5)
    red = mat("DamageRed", (0.95, 0.04, 0.03, 1), emission=0.4)
    green = mat("IntactGreen", (0.03, 0.78, 0.20, 1), emission=0.35)
    fur = mat("Fur", (0.49, 0.27, 0.12, 1), roughness=0.85)
    muzzle = mat("Muzzle", (0.70, 0.43, 0.21, 1), roughness=0.82)
    hoodie = mat("Hoodie", (0.08, 0.48, 0.82, 1), roughness=0.58)
    warm = mat("WarmTable", (0.58, 0.25, 0.08, 1), roughness=0.62)
    crack_mat = mat("PhysicalCrack", (0.004, 0.006, 0.010, 1), roughness=0.24)

    # High-key studio.
    cube("Cyclorama", (0, 3.4, 8.0), (15, 0.5, 36), white, 0.4)
    cube("Floor", (0, 0, -3.3), (13, 12, 0.35), white, 0.25)
    # The table sits in front of the torso but behind the phone/impact rig in
    # camera depth, so it grounds the mascot without hiding the causal action.
    cube("TableTop", (0, -0.55, -1.95), (14, 1.5, 0.34), warm, 0.16)
    cube("TableFront", (0, -0.50, -3.15), (14, 0.65, 2.35), warm, 0.12)
    for loc, energy, size in (((-5, -5, 11), 1500, 7), ((5, -4, 8), 1100, 6), ((0, 2, 12), 900, 5)):
        bpy.ops.object.light_add(type="AREA", location=loc)
        light = bpy.context.object
        light.data.energy, light.data.size = energy, size
        light.data.use_shadow = True
        look_at(light, (0, 0, 2))

    # Camera rig: one animated camera with three functional shot families.
    bpy.ops.object.camera_add(location=(0, -24, 4.5))
    camera = bpy.context.object
    camera.data.type = "ORTHO"
    scene.camera = camera
    camera_points = [
        (0.0, (1.8, -22, 0.8), 8.2), (0.70, (0, -24, 3.2), 15.0),
        (4.2, (0, -24, 3.2), 15.0), (5.8, (0, -24, 4.0), 17.0),
        (7.1, (1.7, -22, 0.8), 8.5), (7.7, (0, -24, 3.2), 15.0),
        (12.2, (0, -25, 5.2), 19.0), (14.2, (1.7, -22, 0.8), 9.0),
        (14.8, (0, -24, 3.2), 15.0), (19.2, (0, -26, 7.0), 22.0),
        (20.5, (0, -27, 9.5), 27.0), (23.2, (0, -28, 8.0), 25.0),
        (29.0, (0, -24, 3.2), 16.0), (31.1, (1.7, -22, 0.8), 9.0),
        (33.2, (0, -24, 2.7), 14.0), (36.1, (0, -25, 4.5), 15.0),
        (38.0, (0, -27, 8.5), 21.0), (39.2, (0, -28, 10.0), 22.0),
        (41.0, (0, -27, 8.5), 22.0), (44.2, (0, -24, 3.2), 15.0),
        (49.2, (0, -24, 3.2), 15.0), (51.5, (1.8, -22, 0.8), 8.2),
    ]
    for time, loc, scale in camera_points:
        camera.location, camera.data.ortho_scale = loc, scale
        target_z = 8.0 if 38.0 <= time <= 41.0 else (2.2 if time < 20 else 4.0)
        look_at(camera, (0, 0, target_z))
        key(camera, time, "location")
        key(camera, time, "rotation_euler")
        camera.data.keyframe_insert(data_path="ortho_scale", frame=frame(time))

    # Camera-locked labels stay mobile-readable in every zoom/pan. Drivers keep
    # their screen position and apparent size proportional to ortho scale.
    def camera_label(name, body, material, y_factor=0.39):
        label = text(name, body, (0, 0, 0), 1.0, material, camera)
        label.rotation_euler = (0, 0, 0)
        label.location = (0, 0, -10)
        for index in (0, 1, 2):
            driver = label.driver_add("scale", index).driver
            var = driver.variables.new()
            var.name, var.targets[0].id, var.targets[0].data_path = "s", camera, "data.ortho_scale"
            driver.expression = "s*0.055"
        driver = label.driver_add("location", 1).driver
        var = driver.variables.new()
        var.name, var.targets[0].id, var.targets[0].data_path = "s", camera, "data.ortho_scale"
        driver.expression = f"s*{y_factor}"
        return label

    cue = camera_label("ProgressionCue", "1 cm  >  1 m  >  10 m  >  100 m", dark, 0.32)
    cue.data.size = 0.48
    for label, display, windows in (
        ("1cm", "DROP 1 cm", [(0, 4.2), (49.2, 51.5)]),
        ("1m", "DROP 1 m", [(4.2, 11.2)]),
        ("10m", "DROP 10 m", [(11.2, 19.2)]),
        ("100m", "DROP 100 m", [(19.2, 49.2)]),
    ):
        marker = camera_label(f"Height_{label}", display, dark)
        marker.data.size = 1.05
        visible(marker, windows)
    # Measuring tower and spring plate.
    tower = cube("TelescopingTower", (-7.0, 0.8, 3.0), (0.55, 0.55, 12.0), silver, 0.12)
    tower.scale.z = 0.12
    animate(tower, [(0, (1, 1, 0.12)), (4.2, (1, 1, 0.35)), (11.2, (1, 1, 0.65)),
                    (19.2, (1, 1, 1.25)), (49.2, (1, 1, 0.12))], "scale")
    plate_root = bpy.data.objects.new("SpringPlateRoot", None)
    bpy.context.collection.objects.link(plate_root)
    plate = cube("ImpactPlate", (1.7, -1.35, -1.55), (4.0, 1.15, 0.38), yellow, 0.24, plate_root)
    springs = []
    for x in (0.55, 1.30, 2.10, 2.85):
        bpy.ops.mesh.primitive_torus_add(major_radius=0.32, minor_radius=0.09, location=(x, -1.35, -1.92), rotation=(math.pi / 2, 0, 0))
        spring = bpy.context.object
        spring.data.materials.append(silver)
        spring.parent = plate_root
        springs.append(spring)
    animate(plate_root, [
        (0, (0, 0, 0)), (0.40, (0, 0, -0.06)), (0.62, (0, 0, 0)),
        (7.30, (0, 0, -0.16)), (7.60, (0, 0, 0)),
        (14.45, (0, 0, -0.30)), (14.72, (0, 0, 0)),
        (31.35, (0, 0, -0.20)), (35.0, (0, 0, -0.20)),
        (35.70, (0, 0, -0.32)), (36.10, (0, 0, -0.32)),
        (36.50, (0, 0, 0.32)), (37.2, (0, 0, 0)), (51.5, (0, 0, 0)),
    ])
    for spring in springs:
        animate(spring, [
            (0, (1, 1, 1)), (0.40, (1, 0.84, 1)), (0.62, (1, 1, 1)),
            (7.30, (1, 0.70, 1)), (7.60, (1, 1, 1)),
            (14.45, (1, 0.52, 1)), (14.72, (1, 1, 1)),
            (31.35, (1, 0.42, 1)), (35.0, (1, 0.42, 1)),
            (35.70, (1, 0.24, 1)), (36.10, (1, 0.24, 1)),
            (36.50, (1, 1.28, 1)), (37.20, (1, 1, 1)), (51.5, (1, 1, 1)),
        ], "scale")

    # One hero phone, with damage layers attached to the same root.
    phone = bpy.data.objects.new("HeroPhone", None)
    bpy.context.collection.objects.link(phone)
    cube("PhoneBody", (0, 0, 0), (2.05, 0.35, 3.55), silver, 0.28, phone)
    cube("PhoneScreen", (0, -0.24, 0.05), (1.76, 0.09, 3.05), dark, 0.20, phone)
    crack_segments = []
    crack_paths = (
        ((0.58, -0.33, 1.15), (0.18, -0.34, 0.70), (-0.05, -0.34, 0.30)),
        ((0.18, -0.34, 0.70), (0.62, -0.34, 0.42)),
        ((-0.05, -0.34, 0.30), (-0.55, -0.34, -0.10), (-0.25, -0.34, -0.72)),
        ((-0.05, -0.34, 0.30), (0.45, -0.34, -0.35), (0.70, -0.34, -1.10)),
    )
    for path_index, path in enumerate(crack_paths):
        for seg_index, (start, end) in enumerate(zip(path, path[1:])):
            crack_segments.append(line_segment(
                f"Crack_{path_index}_{seg_index}", start, end, 0.035,
                crack_mat, phone,
            ))
    for index, segment in enumerate(crack_segments):
        visible(segment, [(7.30 if index < 2 else 14.45, 49.20)])
    h1_open = [
        (0.0, (1.7, -1.60, 1.2), (1, 1, 1), (0, 0, 0.10)),
        (0.20, (1.7, -1.60, 0.85), (1, 1, 1), (0, 0, 0.30)),
        (0.40, (1.7, -1.60, 0.10), (1.08, 0.82, 0.90), (0.22, 0, 0.55)),
        (0.70, (1.3, -1.60, 1.35), (1, 1, 1), (0, 0, 0)),
    ]
    h3_open = [
        (0.0, (1.7, -1.60, -1.8), (1, 0.82, 0.88), (0, 0, 3.2)),
        (0.15, (1.7, -1.60, 5.0), (0.82, 0.68, 0.74), (0, 0, 4.0)),
        (0.30, (1.7, -1.60, 8.5), (0.62, 0.52, 0.58), (0, 0, 4.8)),
        (0.62, (1.7, -1.60, 1.2), (1, 1, 1), (0, 0, 0.10)),
        (0.88, (1.7, -1.60, 0.10), (1.08, 0.82, 0.90), (0.22, 0, 0.55)),
        (1.15, (1.3, -1.60, 1.35), (1, 1, 1), (0, 0, 0)),
    ]
    phone_points = (h1_open if args.hook == "H1" else h3_open) + [
        (4.20, (1.3, -1.60, 1.35), (1, 1, 1), (0, 0, math.pi)),
        (5.80, (1.7, -1.60, 5.2), (0.8, 0.8, 0.8), (0, 0, 0)),
        (7.30, (1.7, -1.60, 0.10), (1.06, 0.84, 0.92), (0.18, 0, 0.7)),
        (7.65, (1.3, -1.60, 1.35), (1, 1, 1), (0, 0, -0.2)),
        (12.20, (1.7, -1.60, 8.0), (0.55, 0.55, 0.55), (0, 0, 0)),
        (14.35, (1.7, -1.60, 0.60), (1, 1, 1), (0.30, 0, 0.78)),
        (14.45, (1.7, -1.60, -0.05), (1.08, 0.78, 0.86), (0.48, 0, 1.05)),
        (14.62, (1.7, -1.60, 0.30), (0.92, 1.0, 1.05), (-0.18, 0, 1.18)),
        (16.70, (1.3, -1.60, 1.35), (1, 1, 1), (0, 0, -0.15)),
        (20.50, (1.7, -1.60, 13.0), (0.18, 0.18, 0.18), (0, 0, 0)),
        (23.50, (1.7, -1.60, 10.0), (0.22, 0.22, 0.22), (0, 0, 0.4)),
        (25.10, (1.7, -1.60, 7.0), (0.48, 0.48, 0.48), (0, 0, 0.9)),
        (26.70, (1.7, -1.60, 3.5), (0.82, 0.82, 0.82), (0, 0, 1.5)),
        (31.35, (2.9, -1.60, 0.10), (1, 1, 1), (0, 0, 2.2)),
        (33.20, (1.7, -1.60, -0.30), (1, 1, 1), (0, 0, 2.8)),
        (35.55, (1.7, -1.60, 0.00), (1, 1, 1), (0.42, 0, 2.62)),
        (35.70, (1.7, -1.60, -0.80), (1.18, 0.56, 0.72), (0.62, 0.08, 2.92)),
        (36.05, (1.7, -1.60, -0.35), (0.88, 1.08, 0.92), (-0.28, 0, 3.28)),
        (36.50, (1.7, -1.60, 1.5), (1, 0.8, 0.9), (0, 0, 3.6)),
        (39.20, (2.0, -1.60, 10.0), (0.8, 0.65, 0.7), (0, 0, 5.0)),
        (44.20, (2.6, -1.60, 1.8), (1, 0.78, 0.86), (0, 0, 6.2)),
        (47.20, (2.8, -1.60, 1.1), (1, 0.72, 0.82), (0, 0, 6.4)),
        (49.20, (1.7, -1.60, 2.2), (1, 1, 1), (0, 0, 0.10)),
        (51.50, (1.7, -1.60, 1.2), (1, 1, 1), (0, 0, 0.10)),
    ]
    for time, loc, scale, rotation in phone_points:
        phone.location, phone.scale, phone.rotation_euler = loc, scale, rotation
        key(phone, time, "location"); key(phone, time, "scale"); key(phone, time, "rotation_euler")

    # Local production-specific capy rig.
    capy = bpy.data.objects.new("CapyRoot", None)
    bpy.context.collection.objects.link(capy)
    capy.location = (-1.0, 0, 0)
    torso = sphere("Torso", (0, 0.2, 0.2), (1.55, 0.80, 2.05), hoodie, capy)
    head = sphere("Head", (0, -0.05, 3.10), (1.58, 0.86, 1.28), fur, capy)
    sphere("Muzzle", (0, -0.88, 2.80), (1.12, 0.38, 0.45), muzzle, capy)
    ears = [sphere(f"Ear{side}", (side * 1.0, -0.02, 4.15), (0.28, 0.20, 0.30), fur, capy) for side in (-1, 1)]
    eyes, pupils, brows = [], [], []
    for side in (-1, 1):
        eyes.append(sphere(f"Eye{side}", (side * 0.55, -0.84, 3.40), (0.38, 0.16, 0.33), white, capy))
        pupils.append(sphere(f"Pupil{side}", (side * 0.50 + 0.10, -1.02, 3.36), (0.14, 0.08, 0.17), dark, capy))
        brows.append(cube(f"Brow{side}", (side * 0.55, -1.03, 3.88), (0.60, 0.10, 0.10), dark, 0.04, capy))
    mouths = {
        "neutral": cube("MouthNeutral", (0, -1.16, 2.58), (0.48, 0.08, 0.08), dark, 0.03, capy),
        "smug": text("MouthSmug", "u", (0, -1.18, 2.58), 0.62, dark, capy),
        "flinch": text("MouthFlinch", "~", (0, -1.18, 2.56), 0.70, dark, capy),
        "shock": sphere("MouthShock", (0, -1.13, 2.55), (0.32, 0.08, 0.42), dark, capy),
        "panic": sphere("MouthPanic", (0, -1.13, 2.50), (0.46, 0.08, 0.62), dark, capy),
        "dazed": text("MouthDazed", "~", (0, -1.18, 2.54), 0.62, dark, capy),
    }
    visible(mouths["neutral"], [(0, 0.25), (0.70, 1.35), (4.2, 7.1), (9.2, 12.2), (19.2, 29.0), (31.55, 35.0), (49.2, 51.5)])
    visible(mouths["smug"], [(1.35, 4.2)])
    visible(mouths["flinch"], [(0.25, 0.70), (7.1, 9.2)])
    visible(mouths["shock"], [(12.2, 19.2)])
    visible(mouths["panic"], [(29.0, 31.55), (35.0, 44.2)])
    visible(mouths["dazed"], [(44.2, 49.2)])
    shoulders = [sphere(f"Shoulder{s}", (s * 1.0, -0.20, 1.25), (0.48, 0.36, 0.52), hoodie, capy) for s in (-1, 1)]
    paws = [sphere(f"Paw{s}", (s * 1.15, -0.72, 0.75), (0.46, 0.28, 0.46), muzzle, capy) for s in (-1, 1)]
    arms = []
    for side in (-1, 1):
        curve = bpy.data.curves.new(f"ArmCurve{side}", "CURVE")
        curve.dimensions, curve.bevel_depth, curve.bevel_resolution = "3D", 0.20, 3
        spline = curve.splines.new("BEZIER")
        spline.bezier_points.add(2)
        for point in spline.bezier_points:
            point.handle_left_type = point.handle_right_type = "AUTO"
        arm = bpy.data.objects.new(f"ConnectedArm{side}", curve)
        bpy.context.collection.objects.link(arm)
        arm.data.materials.append(hoodie)
        arm.parent = capy
        arms.append((arm, spline, side))

    def key_arm(spline, side, time, paw_x, paw_z):
        shoulder = Vector((side * 1.0, -0.28, 1.30))
        paw = Vector((side * paw_x, -0.74, paw_z))
        elbow = shoulder.lerp(paw, 0.52) + Vector((side * 0.18, -0.05, -0.12))
        for point, value in zip(spline.bezier_points, (shoulder, elbow, paw)):
            point.co = value
            point.keyframe_insert(data_path="co", frame=frame(time))

    def key_arm_to(spline, side, time, paw_location):
        shoulder = Vector((side * 1.0, -0.28, 1.30))
        paw = Vector(paw_location)
        elbow = shoulder.lerp(paw, 0.52) + Vector((side * 0.16, -0.05, 0.10))
        for point, value in zip(spline.bezier_points, (shoulder, elbow, paw)):
            point.co = value
            point.keyframe_insert(data_path="co", frame=frame(time))

    # Five core pose families plus a short hook-impact flinch. Each controls
    # eyes, pupils, brows, head, torso/root, shoulders, paws, and ears.
    pose_specs = {
        "ready_release": (0.0, 1.05, 0.02, 0.00, 0.05, 0.75, 0.0),
        "hook_flinch": (0.40, 0.42, 0.30, -0.12, -0.10, 0.45, 0.12),
        "smug": (1.35, 0.70, -0.18, -0.10, 0.18, 1.10, -0.08),
        "wince_inspect": (7.65, 0.38, 0.32, 0.16, -0.18, 0.30, 0.10),
        "shock_brace": (14.45, 1.35, -0.38, -0.18, -0.28, 0.05, -0.16),
        "panic_airborne": (38.0, 1.65, 0.42, 0.30, 0.38, 1.45, 0.22),
        "dazed_recovery": (44.20, 0.58, 0.12, -0.24, -0.14, 1.20, -0.18),
    }
    for name, (time, eye_z, brow_angle, head_angle, torso_angle, paw_x, ear_angle) in pose_specs.items():
        for eye in eyes:
            eye.scale.z = eye_z; key(eye, time, "scale")
        for index, pupil in enumerate(pupils):
            pupil.location.x = (-0.50 if index == 0 else 0.50) + (0.20 if name != "panic_airborne" else 0)
            pupil.location.z = 3.36 + (0.20 if name == "panic_airborne" else -0.05)
            key(pupil, time, "location")
        for index, brow in enumerate(brows):
            brow.rotation_euler.y = brow_angle * (-1 if index == 0 else 1)
            key(brow, time, "rotation_euler")
        head.rotation_euler.y = head_angle; key(head, time, "rotation_euler")
        torso.rotation_euler.y = torso_angle; key(torso, time, "rotation_euler")
        for index, shoulder in enumerate(shoulders):
            shoulder.rotation_euler.y = torso_angle * (-1 if index == 0 else 1)
            key(shoulder, time, "rotation_euler")
        for index, paw in enumerate(paws):
            paw.location.x = (-paw_x if index == 0 else paw_x)
            paw.location.z = 0.75 + (0.9 if name in {"shock_brace", "panic_airborne"} else 0)
            key(paw, time, "location")
        for _arm, spline, side in arms:
            key_arm(spline, side, time, paw_x, 0.75 + (0.9 if name in {"shock_brace", "panic_airborne"} else 0))
        for index, ear in enumerate(ears):
            ear.rotation_euler.y = ear_angle * (-1 if index == 0 else 1)
            key(ear, time, "rotation_euler")
    # Loop reset reuses ready_release; it is not a sixth pose family.
    ready = pose_specs["ready_release"]
    reset_time, eye_z, brow_angle, head_angle, torso_angle, paw_x, ear_angle = (49.2, *ready[1:])
    for eye in eyes:
        eye.scale.z = eye_z; key(eye, reset_time, "scale")
    for index, pupil in enumerate(pupils):
        pupil.location.x = (-0.50 if index == 0 else 0.50) + 0.20
        pupil.location.z = 3.31
        key(pupil, reset_time, "location")
    for index, brow in enumerate(brows):
        brow.rotation_euler.y = brow_angle * (-1 if index == 0 else 1)
        key(brow, reset_time, "rotation_euler")
    head.rotation_euler.y = head_angle; key(head, reset_time, "rotation_euler")
    torso.rotation_euler.y = torso_angle; key(torso, reset_time, "rotation_euler")
    for index, shoulder in enumerate(shoulders):
        shoulder.rotation_euler.y = torso_angle * (-1 if index == 0 else 1)
        key(shoulder, reset_time, "rotation_euler")
    for index, paw in enumerate(paws):
        paw.location.x = -paw_x if index == 0 else paw_x
        paw.location.z = 0.75
        key(paw, reset_time, "location")
    for _arm, spline, side in arms:
        key_arm(spline, side, reset_time, paw_x, 0.75)
    for index, ear in enumerate(ears):
        ear.rotation_euler.y = ear_angle * (-1 if index == 0 else 1)
        key(ear, reset_time, "rotation_euler")
    # Grip beats: both paws bracket the one hero phone and the connected arms
    # follow them. This removes the detached "telekinetic phone" read.
    grip_poses = {
        1.35: ((1.20, -1.75, 1.45), (3.30, -1.75, 1.45)),
        4.20: ((1.20, -1.75, 1.45), (3.30, -1.75, 1.45)),
        7.65: ((1.20, -1.75, 1.42), (3.30, -1.75, 1.42)),
        9.20: ((1.20, -1.75, 1.42), (3.30, -1.75, 1.42)),
        16.70: ((1.20, -1.75, 1.40), (3.30, -1.75, 1.40)),
        19.20: ((1.20, -1.75, 1.40), (3.30, -1.75, 1.40)),
        44.20: ((2.55, -1.75, 1.70), (4.15, -1.75, 1.70)),
        47.20: ((2.55, -1.75, 1.35), (4.15, -1.75, 1.35)),
    }
    for time, locations in grip_poses.items():
        for index, (paw, location) in enumerate(zip(paws, locations)):
            paw.location = location
            key(paw, time, "location")
            _arm, spline, side = arms[index]
            key_arm_to(spline, side, time, location)
    animate(capy, [
        (0, (-1, 0, 0)), (14.45, (-1, 0, -0.15)), (19.2, (-1, 0, 0)),
        (29.0, (-1, 0, -0.30)), (36.1, (-1, 0, -0.45)),
        (38.0, (-1, 0, 1.4)), (39.2, (-1.6, 0, 8.0)), (41.0, (-2.0, 0, 9.0)),
        (44.2, (-0.8, 0, 1.2)), (47.2, (-1, 0, 0)), (51.5, (-1, 0, 0)),
    ])

    # Dazed payoff: X pupils and orbiting stars make the final reaction readable
    # even when the face is reduced to phone-feed size.
    for side in (-1, 1):
        dazed_eye = text(f"DazedEye{side}", "X", (side * 0.55, -1.16, 3.40), 0.34, dark, capy)
        visible(dazed_eye, [(44.20, 49.20)])
    for index, (x, z) in enumerate(((-1.55, 4.70), (0.0, 5.05), (1.55, 4.65))):
        star = text(f"DazedStar{index}", "*", (x, -1.10, z), 0.46, yellow, capy)
        visible(star, [(44.20, 47.20)])
        animate(star, [(44.20, (x, -1.10, z)), (45.60, (-x, -1.10, z + 0.22)),
                       (47.20, (x, -1.10, z))], interpolation="LINEAR")

    # Result rail uses compact silhouettes, never extra hero phones.
    rail_x = (-3.1, -1.05, 1.0, 3.05)
    rail_events = ((0, 4.20, green, 0.0), (1, 11.20, yellow, 0.10),
                   (2, 19.20, red, 0.22), (3, 47.20, red, 0.38))
    for index, at, color, bend in rail_events:
        # Clear every result silhouette before the 49.2s camera/title reset;
        # otherwise world-space cards enlarge into and obscure the loop contract.
        rail_windows = ([(at, 29.0), (44.2, 49.2)] if at < 29.0 else [(at, 49.2)])
        silhouette = cube(f"ResultRail_{index}", (rail_x[index], -0.3, 7.0), (1.15, 0.16, 1.9), color, 0.18)
        silhouette.rotation_euler.y = bend
        visible(silhouette, rail_windows)
        if bend:
            rail_crack = line_segment(
                f"ResultCrack_{index}", (rail_x[index] - 0.30, -0.42, 7.35),
                (rail_x[index] + 0.28, -0.43, 6.72), 0.025, dark,
            )
            visible(rail_crack, rail_windows)

    # Compact mid-roll CTA begins inside the required 38-42s window while the
    # capy, phone and debris continue their airborne payoff motion.
    for label, start, end, x in (("LIKE", 38.2, 38.8, -2.8), ("SUB", 38.8, 39.4, 0), ("COMMENT", 39.4, 40.0, 2.8)):
        panel = cube(f"CTA_{label}", (x, -0.5, -0.8), (2.45, 0.16, 0.95), cyan, 0.22)
        caption = text(f"CTA_Text_{label}", label, (x, -0.72, -0.8), 0.38 if label == "COMMENT" else 0.50, dark)
        visible(panel, [(start, end)]); visible(caption, [(start, end)])

    # Event debris and H3-only flash-forward grammar.
    for index in range(12):
        angle = index * math.tau / 12
        debris = cube(f"Debris{index}", (1.7, -0.6, -2.1), (0.20, 0.16, 0.22), red if index % 2 else yellow, 0.04)
        visible(debris, [(36.1, 44.8)])
        animate(debris, [(36.1, (1.7, -0.6, -2.1)), (39.2, (1.7 + 4 * math.cos(angle), -0.6, 6 + 4 * math.sin(angle))),
                         (44.8, (1.7 + 2 * math.cos(angle), -0.6, -2.0))], interpolation="LINEAR")
    if args.hook == "H3":
        flash = text("H3FlashForward", "100m!", (0, -1.2, 5.5), 1.2, red)
        rewind = text("H3Rewind", "<<", (0, -1.2, 3.2), 1.0, cyan)
        visible(flash, [(0, 0.30)]); visible(rewind, [(0.30, 0.62)])

    # The reliable moving watermark is composited in mux_final(), in screen
    # coordinates. Keep no 3D duplicate that can cross the face during pans.
    watermark = text("Watermark", "@ZAPBARA", (0, 0, 0), 0.22, dark, camera)
    watermark.hide_render = True
    watermark.rotation_euler = (0, 0, 0)
    watermark.location = (-3.3, -6.0, -10)
    for index in (0, 1, 2):
        driver = watermark.driver_add("scale", index).driver
        var = driver.variables.new()
        var.name, var.targets[0].id, var.targets[0].data_path = "s", camera, "data.ortho_scale"
        driver.expression = "s*0.045"
    # Safe in-frame route avoids labels, CTA and the character/phone action.
    for time, x_factor, y_factor in ((0, -0.34, -0.40), (18, 0.34, -0.40),
                                     (34, 0.34, 0.28), (51.5, -0.34, -0.40)):
        watermark.location.x = x_factor * camera.data.ortho_scale
        watermark.location.y = y_factor * camera.data.ortho_scale
        key(watermark, time, "location")

    BLEND_FILE.parent.mkdir(parents=True, exist_ok=True)
    bpy.ops.wm.save_as_mainfile(filepath=str(BLEND_FILE))
    if args.preview:
        PREVIEW_DIR.mkdir(parents=True, exist_ok=True)
        for time in PREVIEW_TIMES:
            scene.frame_set(frame(time))
            scene.render.filepath = str(PREVIEW_DIR / f"{args.hook}_{time:05.2f}.png")
            bpy.ops.render.render(write_still=True)
    elif args.benchmark_stage:
        BENCHMARK_DIR.mkdir(parents=True, exist_ok=True)
        for time in BENCHMARK_TIMES:
            scene.frame_set(frame(time))
            scene.render.filepath = str(BENCHMARK_DIR / f"s{args.samples}_{time:05.2f}.png")
            bpy.ops.render.render(write_still=True)
    elif args.render_range:
        start, end = args.render_range
        scene.frame_start, scene.frame_end = start, end
        target = WORK / f"frames_{args.hook}"
        target.mkdir(parents=True, exist_ok=True)
        scene.render.filepath = str(target / "frame_")
        bpy.ops.render.render(animation=True)


def main() -> None:
    if "--blender-stage" in sys.argv:
        blender_stage(sys.argv[sys.argv.index("--") + 1:] if "--" in sys.argv else [])
        return
    parser = argparse.ArgumentParser()
    parser.add_argument("--preview", action="store_true")
    parser.add_argument("--hook", choices=("H1", "H3"), default="H1")
    parser.add_argument("--benchmark", action="store_true")
    parser.add_argument("--frames", type=parse_range)
    parser.add_argument("--samples", type=int, choices=(16, 32, 64), default=DEFAULT_SAMPLES)
    parser.add_argument("--reset-cache", action="store_true", help="Delete generated frames for the selected hook before rendering")
    parser.add_argument("--encode-hook", action="store_true", help="Encode already rendered 0-3s hook frames")
    args = parser.parse_args()
    load_storyboard()
    if args.reset_cache:
        reset_cache(args.hook)
    if args.preview:
        preview(args.hook)
    elif args.benchmark:
        benchmark()
    elif args.frames:
        render_frames(args.frames, args.hook, args.samples)
    elif args.encode_hook:
        encode_visual(args.hook, duration=3.0, samples=args.samples)
    else:
        build_full(args.samples)


if __name__ == "__main__":
    main()
